musicTribes/musicTribes/urls.py
from django.contrib import admin
from django.urls import path, include
from tribes import views as tribes_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('register.urls')),
    path('',include("tribes.urls")),
]

musicTribes/register/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from . import views as v
from django.contrib.auth import views as auth_views


app_name="register"

urlpatterns = [
    path('', v.homepage, name="homepage"),
    path('register/', v.register, name="register"),
    path('login/',v.login_request, name="login"),
    path('logout/',v.logout_request, name="logout"),
    path('update_profile/',v.update_profile, name="update_profile"),
    path('change_password/',v.change_password, name="change_password")
]

musicTribes/tribes/urls.py
from .urls import *
from django.urls import path
from . import views

app_name="tribes"

urlpatterns=[
    path('',views.index, name="index"),
    path('create_tribe/',views.create_tribe, name="create_tribe"),
    path('<int:tribe_id>/create_playlist/',views.create_playlist, name="create_playlist"),
    path("<int:tribe_id>/",views.tribe,name="tribe"),
    path("<int:tribe_id>/<int:playlist_id>/playlist/",views.playlist,name="playlist"),
    path('<int:tribe_id>/join_tribe/',views.join_tribe, name="join_tribe"),
    path("<int:tribe_id>/<int:playlist_id>/like/",views.like,name="like"),
    path('<int:tribe_id>/leave_tribe/',views.leave_tribe, name="leave_tribe"),
    path('<int:tribe_id>/kick_user/<int:user_id>',views.kick_user, name="kick_user"),
    path("<int:tribe_id>/<int:playlist_id>/add_comment/",views.add_comment, name="add_comment"),
    path('delete_tribe/<int:tribe_id>/',views.delete_tribe, name="delete_tribe"),
    path('delete_playlist/<int:playlist_id>/',views.delete_playlist, name="delete_playlist"),
    path('add_song/<int:playlist_id>/',views.add_song, name="add_song"),
    path('add_like/<int:song_id>/<int:playlist_id>/',views.add_like, name="add_like"),
    path("<int:tribe_id>/<int:playlist_id>/like/<int:comment_id>",views.like, name="like"),
]

musicTribes/tribes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields.related import ForeignKey
from django.utils import timezone
# Create your models here.

class Tribe(models.Model):
    chieftain = models.ForeignKey(User, on_delete=models.CASCADE,related_name="chieftain")
    name = models.CharField(unique=True,max_length=50,blank=False)
    logourl = models.CharField(max_length=1000,
            default="https://www.pngitem.com/pimgs/m/180-1802939_tribe-gaming-logo-tribe-gaming-hd-png-download.png",
            blank=False)
    description = models.TextField(max_length=1000)
    genre = models.CharField(max_length=20,blank=False)
    members=models.ManyToManyField(User,blank=True)
    

    
    # def chieftain(self):
    #     return self.chieftain

    def created_by(self):
        return self.chieftain.user.username

    def __str__(self):
        return self.name

class Song(models.Model):
    #playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE,related_name="playlist")
    user=models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    name=models.CharField(max_length=200)
    artist=models.CharField(max_length=200)
    urlsong=models.CharField(max_length=500,blank=True)
    likes=models.ManyToManyField(User,blank=True, related_name="likes")
    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.name    
    
class Playlist(models.Model):
    name=models.CharField(max_length=100)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    songs=models.ManyToManyField(Song)
    description = models.TextField(max_length=1000)
    tribe  = models.ForeignKey(Tribe,on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Comment(models.Model):
    playlist=models.ForeignKey(Playlist, blank=True, related_name="comments", on_delete=models.CASCADE)
    user=models.ForeignKey(User, blank=True, on_delete=models.CASCADE)
    text=models.TextField()
    date=models.DateTimeField(default=timezone.now)
    #likes=models.ManyToManyField(User,blank=True, related_name="likes")

  
    def __str__(self):
        return self.user.username

    

musicTribes/tribes/forms.py
from django.db.models import fields
from .models import *
from django.forms import ModelForm

class TribeForm(ModelForm):
    class Meta:
        model = Tribe
        fields = ['name', 'description','genre', 'logourl']

class PlaylistForm(ModelForm):
    class Meta:
        model = Playlist
        fields = ['name','description']

class SongForm(ModelForm):
    class Meta:
        model = Song
        fields = ['name','artist','urlsong']

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields=['text']
        
        

musicTribes/tribes/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.urls import reverse
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
# Create your views here.

def index(request):
    tribes = Tribe.objects.all()
    user=request.user
    chieftain_tribes = []
    member_tribes = []
    non_member_tribes = []
    for tribe in tribes :
        if user.id == tribe.chieftain.id:
            chieftain_tribes.append(tribe)
        elif user in tribe.members.all():
            member_tribes.append(tribe)
        else :
            non_member_tribes.append(tribe)
    return render(request,'tribes/tribes.html',context={'chieftain_tribes': chieftain_tribes,
                     'member_tribes':member_tribes, 'non_member_tribes':non_member_tribes})
@login_required
def tribe(request, tribe_id):
    user=request.user.profile
    user_tribes=user.tribes.all()

    user_in_tribe=0

    tribe = Tribe.objects.filter(id=tribe_id).first()
    members = tribe.members.all()
    chieftain_id = tribe.chieftain.id
    user_id = request.user.id
    user_is_admin = user.is_admin
    if user_id == chieftain_id :
        user_chieftain=1
    else :
        user_chieftain=0
    print(user_chieftain)
    if tribe in user_tribes : 
        user_in_tribe=1
    playlists = Playlist.objects.filter(tribe=tribe)
    context = {"tribe":tribe,"playlists":playlists,"user_in_tribe":user_in_tribe, "members":members , "user_chieftain": user_chieftain, "user_is_admin": user_is_admin}
    return render(request,'tribes/tribe.html',context)

@login_required
def create_tribe(request):
    user=request.user.profile
    form = TribeForm(request.POST)
    if form.is_valid():
        saved_tribe = form.save(commit=False)
        saved_tribe.chieftain = request.user
        saved_tribe.save()
        saved_tribe.members.add(request.user)
        user.tribes.add(saved_tribe.id)
        return HttpResponseRedirect(reverse('tribes:tribe',args=(saved_tribe.id,)))
    else:
        form=TribeForm()
    context = {'form':form}
    return render(request,'tribes/create_tribe.html',context)

@login_required
def delete_tribe(request, tribe_id):
    user=request.user.profile
    tribe = Tribe.objects.filter(id=tribe_id).first()
    context = {}
    if request.user.id == tribe.chieftain.id or user.is_admin == 1 :
        tribe.delete()
        deleted = 1
    else :
        deleted = 0
    context['deleted']=deleted
    return render(request,'tribes/delete_tribe.html',context)

@login_required
def delete_playlist(request, playlist_id):
    user=request.user.profile
    playlist = Playlist.objects.filter(id=playlist_id).first()
    tribe=playlist.tribe
    context = {}
    if request.user.id == tribe.chieftain.id or user.is_admin == 1 or user.id == playlist.user.id:
        playlist.delete()
        deleted = 1
    else :
        deleted = 0
    context['deleted']=deleted
    return render(request,'tribes/delete_playlist.html',context)

def like(request, tribe_id):
    comment=get_object_or_404(Comment, id=request.POST.get('comment_id'))
    comment.likes.add(request.user)
    return HttpResponseRedirect(reverse('tribes:tribe',args=(tribe_id,)))

def add_like(request, song_id, playlist_id):
    song=Song.objects.get(id=song_id)
    song.likes.add(request.user)
    playlist=Playlist.objects.get(id=playlist_id)
    tribe_id=playlist.tribe.id
    return HttpResponseRedirect(reverse('tribes:playlist',args=(tribe_id, playlist_id,)))

def add_song(request, playlist_id):
    form = SongForm(request.POST)
    if form.is_valid():
        saved_song=form.save(commit=False)
        saved_song.user = request.user
        saved_song.save()
        playlist=Playlist.objects.get(id=playlist_id)
        tribe_id=playlist.tribe.id
        playlist.songs.add(saved_song)
        playlist.save()
        return HttpResponseRedirect(reverse('tribes:playlist',args=(tribe_id, playlist_id,)))
    else:
        form=SongForm()
    context = {'form':form}
    return render(request,'tribes/add_song.html',context)

        

@login_required
def create_playlist(request, tribe_id):
    form = PlaylistForm(request.POST)
    if form.is_valid():
        saved_playlist = form.save(commit=False)
        saved_playlist.user = request.user
        tribe=Tribe.objects.get(id=tribe_id)
        saved_playlist.tribe=tribe
        saved_playlist.save()
        return HttpResponseRedirect(reverse('tribes:tribe',args=(tribe_id,)))
    else:
        form=PlaylistForm()
    context = {'form':form}
    return render(request,'tribes/create_playlist.html',context)

def playlist(request, tribe_id, playlist_id):
    user=request.user.profile
    user_tribes=user.tribes.all()
    is_admin = user.is_admin
    tribe = Tribe.objects.get(id=tribe_id)
    if tribe in user_tribes:
        is_member=1
    else:
        is_member=0
    playlist = Playlist.objects.filter(tribe=tribe,id=playlist_id).first()
    songs = playlist.songs.all()
    songs_with_likes = []
    for song in songs:
        if request.user in song.likes.all():
            liked=1
        else:
            liked=0
        songs_with_likes.append({'song':song, 'liked':liked, 'number_of_likes':song.total_likes})
    if playlist.tribe.chieftain.id == request.user.id:
        is_chieftain=1
    else:
        is_chieftain=0
    if playlist.user.id == request.user.id:
        is_author = 1
    else:
        is_author=0
    context={"tribe":tribe, "playlist":playlist,"songs_with_likes":songs_with_likes,"is_chieftain":is_chieftain,
                 "is_admin":is_admin, "is_author":is_author, "is_member":is_member}
    return render(request,"tribes/playlist.html",context)

def join_tribe(request, tribe_id):
    tribe=Tribe.objects.get(id=tribe_id)
    tribe.members.add(request.user)
    tribe.save()
    request.user.profile.tribes.add(tribe)
    return redirect(("/"+str(tribe_id)+"/"))

def leave_tribe(request, tribe_id):
    tribe=Tribe.objects.get(id=tribe_id)
    tribe.members.remove(request.user)
    tribe.save()
    request.user.profile.tribes.remove(tribe)
    return redirect(("/"+str(tribe_id)+"/"))

def kick_user(request, user_id , tribe_id):
    tribe=Tribe.objects.get(id=tribe_id)
    kicked_user = User.objects.filter(id=user_id).first()
    tribe.members.remove(request.user)
    tribe.save()
    request.user.profile.tribes.remove(tribe)
    return redirect(("/"+str(tribe_id)+"/"))
    
@login_required
def add_comment(request, playlist_id,tribe_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        saved_comment = form.save(commit=False)
        saved_comment.user = request.user
        playlist=Playlist.objects.get(id=playlist_id)
        saved_comment.playlist=playlist
        saved_comment.save()
        
        
        return HttpResponseRedirect(reverse('tribes:tribe',args=(tribe_id,)))
    else:
        form=CommentForm()
    context = {'add_comment':form}
    return render(request,'tribes/add_comment.html',context)
    

    
   












        

musicTribes/tribes/templates/tribes/add_comment.html
{% extends "tribes/base.html" %}

{% block content %}      

{% load crispy_forms_tags %}


<div class="container py-5">
  <h1>Add comment</h1>
  <form method="POST">
    {% csrf_token %}
    {{ add_comment|crispy }}
    <button class="btn btn-primary" type="submit">Add comment</button>
  </form>
  
</div>

{% endblock %}

musicTribes/tribes/templates/tribes/add_song.html
{% extends "tribes/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<style>
div {
    padding: 10px;
   
  }
  </style>
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
           
            <button type="submit" class="btn btn-success">Add song</button>
        </div>
	
	
	

    </form>
{% endblock %}

musicTribes/tribes/templates/tribes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pocetna</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Music tribes</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'tribes:index' %}">Početna <span class="sr-only">(current)</span></a>
            </li>
            {% if not user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register:register' %}">Register</a>
              </li>
            {% endif %}
                        
            {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link disabled" href="#">{{user.username}}
            <img src="{{user.profile.logo}}" alt="" width="20" height="20">
          </a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'register:logout' %}">Logout</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register:update_profile' %}">Update Profile</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>   
{% block content %}
{% endblock %}
</body>
</html>

musicTribes/tribes/templates/tribes/create_playlist.html
{% extends "tribes/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<style>
div {
    padding: 10px;
   
  }
  </style>
    <form method="POST" class="form-group">
        {% csrf_token %}
        {{ form|crispy }}
        <div>
           
            <button type="submit" class="btn btn-success">Create playlist</button>
        </div>
	
	
	

    </form>
{% endblock %}

musicTribes/tribes/templates/tribes/create_tribe.html
{% extends "tribes/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<style>
	div {
		padding: 10px;
	   
	  }
	  </style>
    <form method="POST" class="form-group">
	{% csrf_token %}
	<div>{{ form|crispy }}
		<button type="submit" class="btn btn-success">Create tribe</button>
	</div>
	
	
    </form>
{% endblock %}

musicTribes/tribes/templates/tribes/delete_playlist.html
{% extends "tribes/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if deleted == 1%}
deleted i gotovo
{% else %}
nemate prava
{% endif %}
{% endblock %}

musicTribes/tribes/templates/tribes/delete_tribe.html
{% extends "tribes/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
{% if deleted == 1%}
deleted i gotovo
{% else %}
nemate prava
{% endif %}
{% endblock %}

musicTribes/tribes/templates/tribes/playlist.html
{% extends "tribes/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<style>
  .container {
height: 70px;
position: relative;

}

.a {
  font-size: 15px;
}

.center {
margin: 0;
position: absolute;
top: 50%;
left: 50%;
-ms-transform: translate(-50%, -50%);
transform: translate(-50%, -50%);
}
  </style>



<br>
<div class="container">
  <div class="center">
    
      <h1>{{tribe.name}}</h1>
      <h1>{{playlist.name}}</h1>

    
  </div>
</div>
<br>
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Song</th>
        <th scope="col">URL</th>
        <th scope="col">Added by</th>
        <th scope="col">Likes</th>
      
      </tr>
    </thead>
    <tbody>
      {% if is_admin == 1 or is_chieftain == 1 or is_author == 1 %}
      <a class="btn btn-primary" href="{% url  'tribes:delete_playlist' playlist.id %}" role="button">Delete playlist</a>
      {% endif %}
      {% if is_admin == 1 or is_chieftain == 1 or is_author == 1 or is_member == 1%}
      <a class="btn btn-primary" href="{% url  'tribes:add_song' playlist.id %}" role="button">Add song</a>
      {% endif %}
        {% for song in songs_with_likes %}
      <tr>
        <td>{{song.song.name}}</td>
        <td>{{song.song.urlsong}}</td>
        <td>{{song.song.user.username}}</td>
        {% if song.liked == 0 %}
        <td class="btn btn-primary"><a href="{% url 'tribes:add_like' song_id=song.song.id playlist_id=playlist.id %}">Like</a>{{song.number_of_likes}}</td>
        {% else %}
        <td>{{song.number_of_likes}}</td>
        {% endif %}
        {% endfor %}
      </tr>
      
    </tbody>
  </table>
  
  {% if user_in_tribe == 1 %}
  <p class="text-center"><a href="{% url 'tribes:add_comment' tribe_id=tribe.id playlist_id=playlist.id %}">Add comment</a>.</p>
  {% else %}
  {% endif %}
  <h2>Comments...</h2>

 
  {% if not playlist.comments.all %}
    No comments yet
  {% else %}
      {% for comment in playlist.comments.all %}
        <strong>
          {{ comment.user }}
          {{ comment.date }}
        </strong>
        <br>
        {{ comment.text }}
        <form action="{% url 'tribes:like' tribe_id=tribe.id playlist_id=playlist.id comment_id=comment.id %}" method="POST">
          {% csrf_token %}
          <button type="submit", name="comment_id",value="{{ playlist.id }}" class="btn btn-primary btn-sm">Like </button>
          <h3>{{ comment.total_likes }}</h3>

        </form>
        </br>
      {% endfor %}
  {% endif %}
  {% endblock %}

musicTribes/tribes/templates/tribes/tribe.html
{% extends "tribes/base.html" %}
{% load static %}

{% block content %}
<style>
  .container {
height: 70px;
position: relative;

}

.a {
  font-size: 15px;
}

.center {
margin: 0;
position: absolute;
top: 50%;
left: 50%;
-ms-transform: translate(-50%, -50%);
transform: translate(-50%, -50%);
}
  </style>



<br>
<div class="container">
  <div class="center">

      <h1>{{tribe.name}}</h1>
      <h1>{{tribe.chieftain.name}}</h1>


  </div>
</div>
<br>
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Playlist name</th>
        <th scope="col">Playlist created by</th>

      </tr>
    </thead>
    <tbody>
      {% for playlist in playlists %}
      <tr>
        <td>{{playlist.name}}</td>
        <td>{{playlist.user}}</td>
        <td><a class="btn btn-primary" href="{% url 'tribes:playlist' tribe_id=tribe.id playlist_id=playlist.id %}">Check Playlist</a></td>
        {% endfor %}
      </tr>

    </tbody>
  </table>
  <div class="container">
    <div class="center">

  {% if user_in_tribe == 0 %}
  <a class="btn btn-primary" href="{% url 'tribes:join_tribe' tribe.id %}" role="button">Join tribe</a>
  {% elif user_in_tribe == 1 %}
  <a class="btn btn-primary" href="{% url 'tribes:leave_tribe' tribe.id %}" role="button">Leave tribe</a>
  <a class="btn btn-primary" href="{% url 'tribes:create_playlist' tribe.id %}" role="button">Create playlist</a>
  {% if user_chieftain == 1 or user_is_admin == 1%}
  <a class="btn btn-primary" href="{% url 'tribes:delete_tribe' tribe.id %}" role="button">Delete tribe</a>
  {% endif %}
  {% else %}
      Error!!
  {% endif %}
    </div>
  </div>

  {% for member in members %}
  <h2>{{member.username}}</h2>
  {% if user_chieftain == 1 or user_is_admin == 1%}
    <a class="btn btn-primary" href="{% url  'tribes:kick_user' tribe.id member.id %}" role="button">Kick user</a>
  {% else %}
  {% endif %}
  {% endfor%}

  {% endblock %}

musicTribes/tribes/templates/tribes/tribes.html
{% extends "tribes/base.html" %}
{% load static %}

{% block content %}
<style>
    .container {
  height: 70px;
  position: relative;
  border: 3px solid rgb(8, 158, 168);
}

.center {
  margin: 0;
  position: absolute;
  top: 50%;
  left: 50%;
  -ms-transform: translate(-50%, -50%);
  transform: translate(-50%, -50%);
}
    </style>
<br>

<div class="container">
    <div class="center">
<a class="btn btn-primary" href="{% url 'tribes:create_tribe' %}" role="button">Create tribe</a>
</div>
</div>
<h2>Chieftain tribes</h2>
{% for tribe in chieftain_tribes %}
<ul>
  <br>
 
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Logo</th>
        <th scope="col">Tribe name</th>
        <th scope="col">Tribe genre</th>
        <th scope="col">Chieftain</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"><img src="{{ tribe.logourl }}" alt="" width="100" height="100"></th>
        
        <td>{{tribe.name}}</td>
        <td>{{tribe.genre}}</td>
        <td>{{tribe.chieftain.username}}</td>
        <td><a class="btn btn-primary" href="{% url 'tribes:tribe' tribe_id=tribe.id %}">Check Tribe</a></td>
      </tr>
      
    </tbody>
  </table>
</ul>
{% endfor %}
<h2>Member tribes</h2>
{% for tribe in member_tribes %}
<ul>
  <br>
 
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Logo</th>
        <th scope="col">Tribe name</th>
        <th scope="col">Tribe genre</th>
        <th scope="col">Chieftain</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"><img src="{{ tribe.logourl }}" alt="" width="100" height="100"></th>
        
        <td>{{tribe.name}}</td>
        <td>{{tribe.genre}}</td>
        <td>{{tribe.chieftain.username}}</td>
        <td><a class="btn btn-primary" href="{% url 'tribes:tribe' tribe_id=tribe.id %}">Check Tribe</a></td>
      </tr>
      
    </tbody>
  </table>
</ul>
{% endfor %}
<h2>Non member tribes</h2>
{% for tribe in non_member_tribes %}
<ul>
  <br>
 
<table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Logo</th>
        <th scope="col">Tribe name</th>
        <th scope="col">Tribe genre</th>
        <th scope="col">Chieftain</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row"><img src="{{ tribe.logourl }}" alt="" width="100" height="100"></th>
        
        <td>{{tribe.name}}</td>
        <td>{{tribe.genre}}</td>
        <td>{{tribe.chieftain.username}}</td>
        <td><a class="btn btn-primary" href="{% url 'tribes:tribe' tribe_id=tribe.id %}">Check Tribe</a></td>
      </tr>
      
    </tbody>
  </table>
</ul>
{% endfor %}

{% endblock %}